apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  volumes:
    - name: work
      emptyDir: {}
  initContainers:
    - name: init
      image: busybox
      command: ["/bin/sh", "-c", "echo 'hello from init' > /work/msg"]
      volumeMounts:
        - name: work
          mountPath: /work
  containers:
  - image: busybox
    name: main
    command: ["/bin/sh", "-c", "tail -f /work/msg && sleep 500"]
    volumeMounts:
      - name: work
        mountPath: /work
