"""
Charsiu G2P backend: language codes, dictionary loader, and ONNX generator.

References
----------
J. Zhu, C. Zhang, and D. Jurgens, "Byt5 model for massively multilingual
grapheme-to-phoneme conversion," 2022.
https://github.com/lingjzhu/CharsiuG2P
"""

LANGUAGE_CODES_CHARSIU = frozenset(
    [
        "ady",
        "afr",
        "amh",
        "ang",
        "ara",
        "arg",
        "arm-e",
        "arm-w",
        "aze",
        "bak",
        "bel",
        "bos",
        "bul",
        "bur",
        "cat",
        "cze",
        "dan",
        "dut",
        "egy",
        "eng-uk",
        "eng-us",
        "enm",
        "epo",
        "est",
        "eus",
        "fas",
        "fin",
        "fra-qu",
        "fra",
        "geo",
        "ger",
        "gle",
        "glg",
        "grc",
        "gre",
        "hbs-cyrl",
        "hbs-latn",
        "hin",
        "hun",
        "ice",
        "ido",
        "ina",
        "ind",
        "isl",
        "ita",
        "jpn",
        "kaz",
        "khm",
        "kor",
        "kur",
        "lat-clas",
        "lat-eccl",
        "lit",
        "ltz",
        "mac",
        "mlt",
        "mri",
        "msa",
        "nan",
        "nob",
        "ori",
        "pap",
        "pol",
        "por-bz",
        "por-po",
        "ron",
        "rus",
        "san",
        "slk",
        "slo",
        "slv",
        "sme",
        "snd",
        "spa-latin",
        "spa-me",
        "spa",
        "sqi",
        "srp",
        "swa",
        "swe",
        "syc",
        "tam",
        "tat",
        "tgl",
        "tha",
        "tts",
        "tuk",
        "tur",
        "uig",
        "ukr",
        "urd",
        "uzb",
        "vie-c",
        "vie-n",
        "vie-s",
        "wel-nw",
        "wel-sw",
        "yue",
        "zho-s",
        "zho-t",
    ]
)
LANGUAGE_CODES_CHARSIU_TO_ISO_639_3 = {
    "arm-e": "hye",  # / 'arm'
    "arm-w": "hyw",
    "fra-qu": "fr-CA",
    "lat-clas": "la",
    "lat-eccl": "la-VA",
    "por-bz": "pt-BR",
    "por-po": "pt-PT",
    "spa-latin": "es-ES",
    "spa-me": "es-MX",
    "vie-c": "vie",
}
